name: Practicing Artifacts

on: 
  workflow_dispatch:

jobs: 
  job-1-create-a-file:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4

       - name: creating a file 
         run: echo "the file was created in the job 1"> file.txt
 
       - name: Uploading Artifact
         uses: actions/upload-artifact@v4
         with: 
          name: share-files
          path: file.txt

  job-2-downloading:
       runs-on: ubuntu-latest
       needs: job-1-create-a-file
       steps: 
         - name: downloading artifact 
           uses: actions/download-artifact@v4
           with:
            name: myfile

         - name: viewing the file which was uploaded 
           run: cat file.txt 

      

      

        
      
       