name: Understanding JOBS 

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  testing-plugins:
     runs-on: ubuntu-latest
     steps:
      - name: checkout my repo 
        uses: actions/checkout@v4
      
      - name: showing files that are taken from my repo 
        run: ls -la
      
       