name: Understanding Jobs

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  explore-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Who am I?
        run: |
          echo "User:"
          whoami
          echo "Current folder:"
          pwd
          echo "Files here:"
          ls -la

      - name: Step 2 - Create a file
        run: |
          echo "This file was created in step 2" > test.txt
          ls -la

      - name: Step 3 - Can I still see the file?
        run: |
          ls -la
